services:
  mongo:
    image: mongo
    # ports:
    #   - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # - mongo-volume:/data/db
      - /data/db
      - ./routes:/data
    networks:
      - mongo-express-network
      - api-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@host.docker.internal:27018/
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    networks:
      - mongo-express-network

  api:
    image: api-session13-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    env_file:
      - .env
    # environment:
    #   - MONGO_URI=mongodb://root:example@mongo:27017/book-store?authSource=admin
    #   - PORT=3001
    networks:
      - api-network

volumes:
  mongo-volume:

networks:
  mongo-express-network:
  api-network:
